config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :movies do
    post :import_csv, on: :collection
    post :import_reviews, on: :collection
    resources :reviews, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews

  def update_ratings
    self.ratings_sum = reviews.sum(:rating)
    self.ratings_count = reviews.count
    save
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  after_create :update_movie_ratings
  after_destroy :update_movie_ratings

  private

  def update_movie_ratings
    movie.update_ratings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    if params[:actor].present?
      @movies = Movie.where("EXISTS (SELECT 1 FROM unnest(actors) actor WHERE actor ILIKE ?)", "%#{params[:actor]}%")
    else
      @movies = Movie.all
    end

    # Calculate average rating and sort movies
    @movies = @movies.select('movies.*, COALESCE(ratings_sum / NULLIF(ratings_count, 0), 0) AS average_rating')
                     .order('average_rating DESC')
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def import_csv
    csv_file = params[:csv_file]

    path = Rails.root.join('tmp', csv_file.original_filename)
    File.open(path, 'wb') do |file|
      file.write(csv_file.read)
    end

    MovieCsvImporter.perform_later(path.to_s)

    redirect_to movies_path, notice: 'CSV import started.'
  end

  def import_reviews
    csv_file = params[:reviews_file]

    path = Rails.root.join('tmp', csv_file.original_filename)
    File.open(path, 'wb') do |file|
      file.write(csv_file.read)
    end

    ReviewImporter.perform_later(path.to_s)

    redirect_to movies_path, notice: 'Reviews import started.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def movie_rating(movie)
    return 0 unless movie.ratings_count > 0

    return  movie.ratings_sum / movie.ratings_count
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuneImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_csv_importer.html.erb
<div class="columns">
  <div class="column">
    <%= form_with(url: import_csv_movies_path, method: :post, multipart: true, local: true, html: { id: 'movie_form' }) do |form| %>
      <div class="file has-name">
        <label class="file-label">
          <%= form.file_field :csv_file, class: 'file-input', id: 'movie_file' %>
          <span class="file-cta">
        <span class="file-label">
          Choose a movie file…
        </span>
      </span>
          <span class="file-name" id="movie_file_name">
        No file uploaded
      </span>
        </label>
      </div>
      <%= form.submit 'Import Movies', class: 'button is-primary', id: 'movie_submit', disabled: true %>
    <% end %>
  </div>
  <div class="column">
    <%= form_with(url: import_reviews_movies_path, method: :post, multipart: true, local: true, html: { id: 'review_form' }) do |form| %>
      <div class="file has-name">
        <label class="file-label">
          <%= form.file_field :reviews_file, class: 'file-input', id: 'review_file' %>
          <span class="file-cta">
        <span class="file-label">
          Choose a review file…
        </span>
      </span>
          <span class="file-name" id="review_file_name">
        No file uploaded
      </span>
        </label>
      </div>
      <%= form.submit 'Import Reviews', class: 'button is-primary', id: 'review_submit', disabled: true %>
    <% end %>
  </div>
</div>

<script>
    document.getElementById('movie_file').addEventListener('change', function(e) {
        document.getElementById('movie_file_name').textContent = e.target.files[0].name;
        document.getElementById('movie_submit').disabled = false;
    });

    document.getElementById('review_file').addEventListener('change', function(e) {
        document.getElementById('review_file_name').textContent = e.target.files[0].name;
        document.getElementById('review_submit').disabled = false;
    });
</script>

app/views/movies/_filter.html.erb
<%= form_with(url: movies_path, method: :get, local: true) do |form| %>
  <div class="field">
    <%= form.label :actor, 'Type in an actors name', class: 'label' %>
    <div class="control">
      <%= form.text_field :actor, class: 'input', value: params[:actor], placeholder: "John Travolta..." %>
    </div>
  </div>
  <div class="control">
    <%= form.submit 'Search', class: 'button is-primary' %>
  </div>
<% end %>

app/views/movies/index.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title">
      Movies
    </p>
    <p class="subtitle">
      Find the best movie to watch tonight!
    </p>
  </div>
</section>

<section class="section">
  <%= render 'filter' %>
</section>

<section class="section">
  <% if @movies.any? %>
    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>Name</th>
        <th>Director</th>
        <th>Actor</th>
        <th>Year</th>
        <th>City</th>
        <th>Country</th>
        <th># Reviews</th>
        <th>Average Rating</th>
      </tr>
      </thead>
      <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= link_to movie.name, movie_path(movie.id) %></td>
          <td><%= movie.director %></td>
          <td><%= movie.actors.join(', ') %></td>
          <td><%= movie.year %></td>
          <td><%= movie.cities.join(', ') %></td>
          <td><%= movie.countries.join(', ') %></td>
          <td><%= movie.reviews.count %></td>
          <td><%= movie_rating(movie) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    It seems like there are no movies in our databases, upload some:
  <% end %>
</section>

<section class="section">
  <%= render 'csv_importer' %>
</section>

app/views/movies/show.html.erb
<section class="hero">
  <div class="hero-body">
    <p class="title">
      <%= @movie.name %>
    </p>
    <p class="subtitle">
      <%= @movie.description  %>
    </p>
    <div class="hero-foot">
      <%= link_to 'Back to Index', movies_path, class: 'button is-primary' %>
    </div>
  </div>
</section>

<section class="section">
  <% if @movie.reviews.any? %>
    <table class="table is-fullwidth">
      <thead>
      <tr>
        <th>User</th>
        <th>Review</th>
        <th>Rating</th>
      </tr>
      </thead>
      <tbody>
      <% @movie.reviews.each do |review| %>
        <tr>
          <td><%= review.username %></td>
          <td><%= review.review %></td>
          <td><%= review.rating %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    It seems like there are no reviews in our databases
  <% end %>
</section>